export default {
  TrafficSignal: "Señal de tráfico",
  Vanilla: "Vainilla",
  SplitPhasing: "Fase de división",
  AdvancedSplitPhasing: "Fase de división avanzada",
  ProtectedRightTurns: "Giros derechos protegidos",
  ProtectedLeftTurns: "Giros izquierdos protegidos",
  Options: "Opciones",
  ExclusivePedestrianPhase: "Fase exclusiva de peatones",
  AlwaysGreenLeftTurns: "Giros izquierdos permitidos en verde",
  AlwaysGreenRightTurns: "Giros derechos permitidos en verde",
  LaneDirectionTool: "Herramienta de dirección de líneas (Experimental)",
  Close: "Cerrar",
  Open: "Abrir",
  Reset: "Restablecer",
  Save: "Guardar",
  PleaseSave: "Por favor guardar los cambios antes de seleccionar otra intersección.",
  PleaseSelectJunction: "Por favor seleccionar una intersección",
  Left: "Izquierda",
  Ahead: "De frente",
  Right: "Derecho",
  UTurn: "Vuelta en U",
  GiveWayToOncomingVehicles: "Give Way to Oncoming Vehicles",
  CustomPedestrianDurationMultiplier: "Pedestrian Phase Duration",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Allow Turning on Red"
};