export default {
  TrafficSignal: "Feux de circulations",
  Vanilla: "Vanilla",
  SplitPhasing: "Feux fractionnés",
  AdvancedSplitPhasing: "Feux fractionnés avancés",
  ProtectedRightTurns: "Virage à droite protégé",
  ProtectedLeftTurns: "Virage à gauche protégé",
  Options: "Options",
  ExclusivePedestrianPhase: "Feux exclusifs piétons",
  AlwaysGreenLeftTurns: "Tourner à gauche toujours vert",
  AlwaysGreenRightTurns: "Tourner à droite toujours vert",
  LaneDirectionTool: "Outil de direction par voie (expérimental)",
  Close: "Fermer",
  Open: "Ouvrir",
  Reset: "Réinitialiser",
  Save: "Sauvegarder",
  PleaseSave: "Veuillez enregistrer les modifications avant de sélectionner une autre intersection.",
  PleaseSelectJunction: "Veuillez sélectionner une intersection",
  Left: "Gauche",
  Ahead: "En face",
  Right: "Droite",
  UTurn: "Demi tour",
  GiveWayToOncomingVehicles: "Give Way to Oncoming Vehicles",
  CustomPedestrianDurationMultiplier: "Pedestrian Phase Duration",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Allow Turning on Red"
};