export default {
  TrafficSignal: "Verkeerslicht",
  Vanilla: "Standaard",
  SplitPhasing: "Gescheiden fasering",
  AdvancedSplitPhasing: "Geavanceerde gescheiden fasering",
  ProtectedRightTurns: "Beschermd rechts afslaan",
  ProtectedLeftTurns: "Beschermd links afslaan",
  Options: "Opties",
  ExclusivePedestrianPhase: "Exclusieve voetgangers fase",
  AlwaysGreenLeftTurns: "Altijd Groen Linksaf",
  AlwaysGreenRightTurns: "Altijd Groen Rechtsaf",
  LaneDirectionTool: "Voorsorteren (Experimenteel)",
  Close: "Sluiten",
  Open: "Openen",
  Reset: "Herstellen",
  Save: "Opslaan",
  PleaseSave: "Sla de wijzigingen op voordat u een andere kruising selecteert.",
  PleaseSelectJunction: "Selecteer een kruising",
  Left: "Links",
  Ahead: "Rechtdoor",
  Right: "Rechts",
  UTurn: "U-bocht",
  GiveWayToOncomingVehicles: "Give Way to Oncoming Vehicles",
  CustomPedestrianDurationMultiplier: "Pedestrian Phase Duration",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Allow Turning on Red"
};