export default {
  TrafficSignal: "Светофор",
  Vanilla: "Ванилла",
  SplitPhasing: "Раздельная пропуск",
  AdvancedSplitPhasing: "Продвинутая раздельная пропуск",
  ProtectedRightTurns: "Защищенные правые повороты",
  ProtectedLeftTurns: "Защищенные левые повороты",
  Options: "Настройки",
  ExclusivePedestrianPhase: "Отдельная фаза для пешеходов",
  AlwaysGreenLeftTurns: "Всегда «зеленый» на левый поворот",
  AlwaysGreenRightTurns: "Всегда «зеленый» на правый поворот",
  LaneDirectionTool: "Настройка направления полос (экспериментально)",
  Close: "Закрыть",
  Open: "Открыть",
  Reset: "Сбросить",
  Save: "Сохранить",
  PleaseSave: "Пожалуйста, сохраните изменения, прежде чем выбирать другой перекресток",
  PleaseSelectJunction: "Пожалуйста, выберите перекресток",
  Left: "Налево",
  Ahead: "Прямо",
  Right: "Направо",
  UTurn: "Разворот",
  GiveWayToOncomingVehicles: "Give Way to Oncoming Vehicles",
  CustomPedestrianDurationMultiplier: "Pedestrian Phase Duration",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Allow Turning on Red"
};